# -*- coding: utf-8 -*-
"""risk_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCtYGYjPigkmBoCjVReasOJ6on5vZ8b7

**Macro Environment:** An overview of global and local economic conditions
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import seaborn as sns

"""1. The Overall Economic Context

Global Perspective: The opening of 2024 was marked by a world economy that, though steering clear of recession, continued to witness steady, albeit sluggish, growth in the range of 2.6-3.2%. Advanced economies experienced modest expansion, but emerging markets were more robust albeit sensitive to external factors. One dominant theme was ongoing core inflation, which though easing, encouraged the major central banks such as the U.S. Federal Reserve to hold off on expected interest rate reductions and keep a "higher-for-longer" rate environment. This context provided tighter global financial conditions and undermined investor sentiment.

South African Context: South Africa's economy experienced substantial headwinds in the period January to June 2024.

Economic Stagnation: GDP growth was still lackluster, with annual forecasts hovering at about a modest 0.9-1.1%.
Political Uncertainty: The main local event was the prelude to the May 2024 national election. The ANC governing party losing its majority for the first time generated much uncertainty and resulted in a Government of National Unity (GNU). Although this was eventually regarded as market-friendly, the lead-up period to and shortly after the election was characterized by increased political and policy risk.
Structural Problems: Underlying structural limitations, especially in logistics and energy, continued to limit the growth potential of the country despite a gratifying halt to load-shedding from March.
"""

holdings_mar_2024 = pd.read_excel('FI Risk Analyst Case Study.xlsx', sheet_name='FI Data (31 March 2024)')
holdings_jun_2024 = pd.read_excel('FI Risk Analyst Case Study.xlsx', sheet_name='FI Data (30 June 2024)')


def classify_asset(asset_name):
    """
    Classifies an asset as 'Government' or 'Non-Government' based on its name.
    This function is central to our analysis.
    """
    if 'SOUTH AFRICA, REPUBLIC OF (GOVERNMENT)' in asset_name:
        return 'Government'
    else:
        return 'Non-Government'

#new category column in each by applying our classification function
holdings_mar_2024['Category'] = holdings_mar_2024['Asset Name'].apply(classify_asset)
holdings_jun_2024['Category'] = holdings_jun_2024['Asset Name'].apply(classify_asset)

#Group by the new category and sum the weight (%) column to find the total allocation
mar_allocation = holdings_mar_2024.groupby('Category')['Weight (%)'].sum()
jun_allocation = holdings_jun_2024.groupby('Category')['Weight (%)'].sum()

#calculate these allocations as a percentage of the total classified portfolio.
total_mar_weight = mar_allocation.sum()
total_jun_weight = jun_allocation.sum()

mar_percentage_allocation = (mar_allocation / total_mar_weight) * 100
jun_percentage_allocation = (jun_allocation / total_jun_weight) * 100

allocation_comparison_df = pd.DataFrame({
    'March 2024 Allocation (%)': mar_percentage_allocation,
    'June 2024 Allocation (%)': jun_percentage_allocation
})

# Print the results of our analysis
print("Analysis Result: Change in Asset Allocation")
print(allocation_comparison_df)

"""Portfolio Insights"""

mar_data = holdings_mar_2024[['Asset ID', 'Asset Name', 'Active Weight (%)']].rename(
    columns={'Active Weight (%)': 'Active Weight Mar'}
)
jun_data = holdings_jun_2024[['Asset ID', 'Asset Name', 'Active Weight (%)']].rename(
    columns={'Active Weight (%)': 'Active Weight Jun'}
)

#merge the two dataframes
movers_df = pd.merge(mar_data, jun_data, on='Asset ID', how='outer', suffixes=('_mar', '_jun'))

#fill NaN values with 0, which would represent a new position or a fully sold position.
movers_df = movers_df.fillna(0)

#calculate the change in active weight
movers_df['Active Weight Change'] = movers_df['Active Weight Jun'] - movers_df['Active Weight Mar']

#correct asset names from the merged dataframe, prioritizing the June name.
movers_df['Asset Name'] = movers_df['Asset Name_jun'].where(movers_df['Asset Name_jun'] != 0, movers_df['Asset Name_mar'])

top_5_buys = movers_df.sort_values(by='Active Weight Change', ascending=False).head(5)
top_5_sells = movers_df.sort_values(by='Active Weight Change', ascending=True).head(5)

print("--- Portfolio Insights: Biggest Active Changes (March to June 2024) ---")

print("\n--- Top 5 Biggest Increases in Active Weight (Buys) ---")
print(top_5_buys[['Asset Name', 'Active Weight Change']].to_string(index=False))

print("\n--- Top 5 Biggest Decreases in Active Weight (Sells) ---")
print(top_5_sells[['Asset Name', 'Active Weight Change']].to_string(index=False))

"""Observations from the Biggest Movers The Python script above identifies the most significant active decisions made by the manager during the second quarter. The results are telling:

Top 5 Biggest Increases (Buys): The five largest increases in active weight were all in South African Government Bonds. The most significant was adding to the R2026 government bond.

Top 5 Largest Decreases (Sells): The largest sale was a decrease in the R2026 government bond (maybe scaling back a previously bigger position), followed by selling down cash ("South African Rand"), then selling down several other government bonds.

Tie-back to Macro and Portfolio Insights

Definite Proof of Defensive Rotation: The report gives us very clear-cut evidence for our "flight to safety" story. The most important active decisions of the manager were to purchase government bonds in exchange for selling corporate debt and lowering cash. This is a definitive and deliberate action to decrease the risk of the portfolio due to the risky macroeconomic and political backdrop we discussed.

Tactical Government Bond Trading: The fact that the same bond (R2026) shows up on both the top buys and top sells lists (though the buy is significantly higher) emphasizes that the manager isn't merely buying the entire government bond market. They are taking active, tactical shots, hopefully based on where they believe the yield curve offers the most value.

Decreasing Cash to Finance Purchases: The buying of "South African Rand" suggests that the manager was using cash reserves to finance these bond purchases, indicating a conscious shift out of cash and into individual, safe securities.

This exercise strongly adds to the above findings, and it's a picture of a manager who, faced with economic volatility, is de-risking the portfolio actively by offloading corporate bonds and investing cash into a carefully chosen basket of government bonds

Historical Evolution
"""

#time series risk metrics data
risk_metrics_ts = pd.read_excel('FI Risk Analyst Case Study.xlsx', sheet_name = 'Risk Metrics (Time Series)')

risk_metrics_ts['ReferenceDate'] = pd.to_datetime(risk_metrics_ts['ReferenceDate'])

#filter the data for the relevant period (Q2 2024)
start_date = '2024-03-31'
end_date = '2024-06-30'
q2_2024_risk_metrics = risk_metrics_ts[
    (risk_metrics_ts['ReferenceDate'] >= start_date) &
    (risk_metrics_ts['ReferenceDate'] <= end_date)
].copy()

fig, axs = plt.subplots(2, 2, figsize=(16, 10))
fig.suptitle('Historical Evolution of Key Portfolio Risk Metrics (Q2 2024)', fontsize=16)

#Plot 1: Tracking Error (Ex Ante)
axs[0, 0].plot(q2_2024_risk_metrics['ReferenceDate'], q2_2024_risk_metrics['Tracking Error (Ex Ante)'], color='blue')
axs[0, 0].set_title('Tracking Error (Ex Ante)')
axs[0, 0].set_ylabel('TE (%)')
axs[0, 0].grid(True, linestyle='--', alpha=0.6)

#Plot 2: Beta
axs[0, 1].plot(q2_2024_risk_metrics['ReferenceDate'], q2_2024_risk_metrics['BetaP'], color='green')
axs[0, 1].set_title('Portfolio Beta')
axs[0, 1].set_ylabel('Beta')
axs[0, 1].grid(True, linestyle='--', alpha=0.6)

# Plot 3: Active Spread Duration
axs[1, 0].plot(q2_2024_risk_metrics['ReferenceDate'], q2_2024_risk_metrics['SpreadDuration (Active)'], color='red')
axs[1, 0].set_title('Active Spread Duration')
axs[1, 0].set_ylabel('Duration (Years)')
axs[1, 0].grid(True, linestyle='--', alpha=0.6)

# Plot 4: Active Credit Spread Duration
axs[1, 1].plot(q2_2024_risk_metrics['ReferenceDate'], q2_2024_risk_metrics['CreditSpreadDur (Active)'], color='purple')
axs[1, 1].set_title('Active Credit Spread Duration')
axs[1, 1].set_ylabel('Duration (Years)')
axs[1, 1].grid(True, linestyle='--', alpha=0.6)

for ax in axs.flat:
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    plt.setp(ax.get_xticklabels(), rotation=45, ha='right')

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('historical_risk_metrics_evolution.png')

# --- Comments on the Historical Evolution ---
print("--- Historical Evolution Analysis (Q2 2024) ---")
print("The plots of key risk metrics from the time series data show the following evolution:")

"""Analysis of Historic Evolution Following are the most important changes noticed in the portfolio during the second quarter of 2024:

Tracking Error (Active Risk) Increased: The tracking error of the portfolio, a quantification of its active risk, increased from 0.79% to 1.05%.

Insight: This is an important observation. Even though the manager moved into "safer" asset classes (government bonds), the active risk of the portfolio increased. That implies that the particular bets made (such as underweighting long-dated government bonds) were strong enough to add to the fund's divergence from its benchmark. The manager was not just embracing the benchmark; they were making firm, certain positions based on their opinions. Portfolio Beta Was Stable and Greater than 1: The Beta of the portfolio remained stable during the quarter, fluctuating only modestly from 1.07 to 1.11.

Insight: An above-1 Beta means the portfolio should be more volatile than the market as a whole. By keeping that anchored, the manager appears to be focused on stock-specific and sector-specific risk rather than taking a large bet on the direction of the market overall. Sensitivity to Credit Spreads Increased: The Active Spread Duration, which reflects sensitivity to credit spread changes, rose from 0.73 to 1.15.

Insight: On the face of it, this goes against the "flight to safety" story. Yet this is accounted for by the large overweight in the 'NINETY ONE CORPORATE BOND-Z' fund. Although the manager sold separate corporate bonds, they rolled up this risk into one big position. What this indicates is that the manager's main credit choice for the whole portfolio now focuses on the success or otherwise of this one fund. These trends suggest a manager who is defensively reallocating the asset class mix (to government bonds) and at the same time taking up active risk through highly targeted, high-conviction wagers.

Detailed Sector Analysis
"""

#Detailed Sectoral Allocation Change
def classify_sector(asset_name):
    """Classifies an asset into a more detailed sector."""
    name = str(asset_name).upper()
    if 'SOUTH AFRICA, REPUBLIC OF (GOVERNMENT)' in name:
        return 'Government'
    elif any(soe in name for soe in ['ESKOM', 'TRANSNET', 'SANRAL', 'RAND WATER']):
        return 'State-Owned Enterprise (SOE)'
    elif any(bank in name for bank in ['FIRSTRAND', 'ABSA', 'STANDARD BANK', 'NEDBANK']):
        return 'Banks'
    elif 'FUND' in name or 'BOND-Z' in name:
        return 'Fund / Collective Investment'
    elif 'RAND' in name and 'SOUTH AFRICAN' in name:
        return 'Cash'
    else:
        return 'Other Corporate'

#apply the detailed classification to both portfolios
holdings_mar_2024['Sector'] = holdings_mar_2024['Asset Name'].apply(classify_sector)
holdings_jun_2024['Sector'] = holdings_jun_2024['Asset Name'].apply(classify_sector)

#calculate the total weight for each sector
mar_sector_alloc = holdings_mar_2024.groupby('Sector')['Weight (%)'].sum()
jun_sector_alloc = holdings_jun_2024.groupby('Sector')['Weight (%)'].sum()

sector_comparison = pd.DataFrame({
    'March 2024 Weight (%)': mar_sector_alloc,
    'June 2024 Weight (%)': jun_sector_alloc
}).fillna(0)

#change in allocation
sector_comparison['Change (%)'] = sector_comparison['June 2024 Weight (%)'] - sector_comparison['March 2024 Weight (%)']

sector_comparison['Abs Change'] = sector_comparison['Change (%)'].abs()
sector_comparison = sector_comparison.sort_values(by='Abs Change', ascending=False).drop(columns=['Abs Change'])

print("--- Additional Highlights: Detailed Sector Allocation Changes (Q2 2024) ---")
print(sector_comparison.to_string())

"""Shift Out of Cash: The most notable one was a -4.64% decrease in cash positions. This is a big positive. This indicates the manager was actually committing capital during this time and not sitting on it.

Government Bonds were the Big Winner: The cash deployed was put to work mostly to lift the allocation to Government bonds (+4.68%). This further supports our central story of a defensive "flight to quality" during times of macroeconomic and political uncertainty. The manager was not only offloading dangerous assets; they were also actively deploying available cash to support the portfolio's safest holdings.

Within SOEs and the Corporate Bond Fund: Despite minor decreases in allocation to Banks and Other Corporates, the stakes in State-Owned Enterprises and the external corporate bond fund remained incredibly consistent. This attests to the fact that the manager's defensive action was tightly focused. They were not shedding all risk assets, but just keeping their particular, high-conviction holdings in SOEs and the expert fund, which they probably think are best placed to manage the economic environment better than single bank bonds.
"""

mar_risk_contrib = holdings_mar_2024.groupby('Sector')['%CR to Active Total Risk'].sum()
jun_risk_contrib = holdings_jun_2024.groupby('Sector')['%CR to Active Total Risk'].sum()

risk_comparison = pd.DataFrame({
    'March 2024 Risk Contribution (%)': mar_risk_contrib,
    'June 2024 Risk Contribution (%)': jun_risk_contrib
}).fillna(0)

risk_comparison['Abs June Risk'] = risk_comparison['June 2024 Risk Contribution (%)'].abs()
risk_comparison = risk_comparison.sort_values(by='Abs June Risk', ascending=False).drop(columns=['Abs June Risk'])

print("--- Risk Analysis: Contribution to Active Risk by Sector ---")
print(risk_comparison.to_string())

mar_risk_contrib = holdings_mar_2024.groupby('Sector')['%CR to Active Total Risk'].sum()
jun_risk_contrib = holdings_jun_2024.groupby('Sector')['%CR to Active Total Risk'].sum()

risk_heatmap_data = pd.DataFrame({
    'March 2024': mar_risk_contrib,
    'June 2024': jun_risk_contrib
}).fillna(0)

plt.figure(figsize=(10, 7))
sns.heatmap(risk_heatmap_data, annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title('Change in Contribution to Active Risk by Sector (Q2 2024)', fontsize=15)
plt.ylabel('Sector')
plt.xlabel('Time Period')
plt.tight_layout()
plt.savefig('risk_contribution_heatmap.png')
plt.show()

june_holdings_copy = holdings_jun_2024.copy()

june_holdings_copy['Abs %CR'] = june_holdings_copy['%CR to Active Total Risk'].abs()

top_5_risk_contributors = june_holdings_copy.sort_values(by='Abs %CR', ascending=False).head(5)

plt.figure(figsize=(12, 8))
colors = ['red' if x < 0 else 'green' for x in top_5_risk_contributors['%CR to Active Total Risk']]
bars = plt.barh(top_5_risk_contributors['Asset Name'], top_5_risk_contributors['%CR to Active Total Risk'], color=colors)
plt.xlabel('% Contribution to Active Total Risk')
plt.title('Top 5 Active Risk Contributors (June 2024)', fontsize=15)
plt.gca().invert_yaxis()
plt.grid(axis='x', linestyle='--', alpha=0.7)

for bar in bars:
    width = bar.get_width()
    label_x_pos = width + 0.05 if width < 0 else width - 0.05
    plt.text(label_x_pos, bar.get_y() + bar.get_height()/2, f'{width:.2f}%',
             va='center', ha='right' if width < 0 else 'left')

plt.tight_layout()
plt.savefig('top_5_risk_contributors_bar.png')
plt.show()

""". Tracking Error and Active Risk

Observation: The charts of historical evolution show that the portfolio's Tracking Error (ex-ante) expanded from 0.79% to 1.05% during the second quarter. Market Interest & Portfolio Effect: An analyst's "interest in the market" is an expression of a view on the uncertain economic and political environment. Here, the manager converted this worry into broader, high-conviction active bets (such as underweighting certain long-term bonds), even while defensively changing the portfolio's overall asset class distribution. The impact on the portfolio is increased potential for straying away from the benchmark, reflecting that the manager is taking their unique views seriously instead of going passive.

Credit Ratings and Credit Risk
Observation: The allocation to Banks and Other Corporates in the portfolio was decreased, whereas that to Government bonds was increased. Market Interest & Portfolio Effect: Due to the manager's focus on the worsening scenario of corporate health, there was a transparent de-risking of credit exposure. By issuing corporate bonds (which have lower credit ratings) and purchasing sovereign debt (which has the best local credit rating), the manager effectively boosted the weighted-average credit quality of the portfolio. This minimizes the exposure of the portfolio to losses due to corporate defaults during a downturn.

VaR (Value at Risk) and Risk Contribution
Observation: Although the data is not given in a particular VaR value, the Contribution to Risk (%CR) analysis is a great proxy for knowing the drivers of future loss. From our Python analysis, it is evident that the risk source dramatically changed. In June, the Government sector was the biggest contributor to active risk. Market Interest & Portfolio Effect: The manager's market perception has led them to concentrate the portfolio risk. The consequence is that active performance of the fund is now less susceptible to the fortunes of individual companies and is instead very much reliant on long-term South African interest rates direction. The portfolio is well positioned to outperform if long-term rates increase or remain elevated, yet would likely underperform if they decline significantly.

Liquidity Risk
Observation: The portfolio's exposure to highly liquid government bonds rose, financed by selling less liquid corporate bonds and investing cash. Market Interest & Portfolio Effect: Concern regarding market stress translates immediately to concern regarding liquidity. During a crisis, the capacity to sell assets without a considerable price decline is very important. The impact on the portfolio of moving from corporate to government bonds is an important strengthening of its liquidity profile. This allows the manager greater leeway to manage possible client redemptions or take advantage of new opportunities without having to sell illiquid assets at a loss.


"""